let mainItemData = [
    {
      id: "strawberry",
      name: "Strawberry",
      price: 9.95,
      desc: "Refreshing blend of ripe strawberries and creamy goodness.",
      img: "images/smoothie1.jpg",
    },
    {
      id: "mango",
      name: "Mango",
      price: 11.25,
      desc: "Tropical delight blending luscious mangoes with creamy goodness.",
      img: "images/smoothie2.jpg",
    },
    {
      id: "kiwi",
      name: "Kiwi",
      price: 10.25,
      desc: "Tropical burst in every sip, refreshing and invigorating.",
      img: "images/smoothie3.jpg",
    },
    {
      id: "pineapple",
      name: "Pineapple",
      price: 8.99,
      desc: "Tropical escape in every sip, blending sweet pineapple for a taste of paradise.",
      img: "images/smoothie4.jpg",
    },
    {
      id: "blueBerry",
      name: "Blue Berry",
      price: 9.25,
      desc: "Refreshing blend of antioxidant-rich blueberries for a burst of vibrant flavor.",
      img: "images/smoothie5.jpg",
    },
    {
      id: "orange",
      name: "Orange",
      price: 6.95,
      desc: "Burst of citrus refreshment in every creamy sip.",
      img: "images/smoothie6.jpg",
    },
    {
      id: "peach",
      name: "Peach",
      price: 8.95,
      desc: "Luscious sip of summer's sweetness.",
      img: "images/smoothie7.jpg",
    },
    {
      id: "banana",
      name: "Banana",
      price: 7.99,
      desc: "Creamy delight in every sip.",
      img: "images/smoothie8.jpeg",
    },
    {
      id: "dragonFruit",
      name: "Dragon Fruit",
      price: 12.25,
      desc: "Vibrant blend of exotic flavor and tropical bliss.",
      img: "images/smoothie9.jpg",
    },
  ];